CREATE PROC KDV_KONTROL_RAPOR_hz01 (@begdate DATE,@enddate DATE) AS

SELECT 
INV.TRCODE 'Fatura Türü',
INV.FICHENO 'Fatura Numarası',
INV.DOCODE 'Fatura Belge Numarası',
INV.DATE_ 'Fatura Tarihi',
CASE WHEN (INV.ACCOUNTED=1 AND INV.ACCFICHEREF >0)  THEN ' Muhasebeleşmiş' else  'Muhasebeleşmemiş' END 'Durum',
CASE STL.LINETYPE WHEN 0 THEN ITM.CODE WHEN 4 THEN SRV.code ELSE DEM.CODE END AS 'Malzeme/Hizmet_Kodu',
--INV.DOCTRACKINGNR'Döküman İzleme Numarası',
STL.LINEEXP'Fatura Açıklaması',
INV.TRCODE,
STL.IOCODE,
STL.LINETYPE,
CASE STL.LINETYPE WHEN 0 THEN ITM.NAME WHEN 4 THEN SRV.DEFINITION_ ELSE DEM.NAME END AS 'Malzeme Açıklaması',
CL.CODE 'Müsteri Kodu',
CL.DEFINITION_ 'Müsteri Ünvani',

STL.AMOUNT    'Hareket_Miktari ',
UNIT.CODE 'Birimi',
STL.PRICE'Birim Fiyat',
STL.VATMATRAH   'Matrah ',
STL.VAT 'Kdv Oranı',
STL.VATAMNT 'Kdv Tutarı', 

SUBSTRING(acc.CODE,1,4) 'KDV Kebir Hesabı',
ACC.CODE 'Kdv Hesap Kodu', 
ACC.DEFINITION_ 'Kdv Hesap Açıklaması',

SUBSTRING(ACC1.CODE,1,4) 'Tev.KDV Kebir Hesabı',
ACC1.CODE 'Tev.KDV Hesap Kodu', 
ACC1.DEFINITION_ ' Tev.KDV Hesap Açıklaması',


ISNULL(ROUND(CASE WHEN PRACCREF>0 THEN (STL.VATMATRAH*STL.VAT/100) * STL.DEDUCTIONPART1/(NULLIF(STL.DEDUCTIONPART2,0)) ELSE 0 END ,2),0) 'Tev.Kdv Tutarı', 

CASE WHEN ROUND(STL.VATAMNT+CASE WHEN PRACCREF>0 THEN (STL.VATMATRAH*STL.VAT/100) * STL.DEDUCTIONPART1/(NULLIF(STL.DEDUCTIONPART2,0)) ELSE 0 END,2) IS NULL THEN STL.VATAMNT
ELSE ROUND(STL.VATAMNT+CASE WHEN PRACCREF>0 THEN (STL.VATMATRAH*STL.VAT/100) * STL.DEDUCTIONPART1/(NULLIF(STL.DEDUCTIONPART2,0)) ELSE 0 END,2) END 'TOPLAM KDV TUTARI',

YEAR( INV.DATE_) 'Yil' , 
CASE MONTH(INV.DATE_)WHEN 1 THEN '01-Ocak' WHEN 2 THEN '02-subat' WHEN 3 THEN '03-Mart' 
WHEN 4 THEN '04-Nisan' WHEN 5 THEN '05-Mayis' WHEN 6 THEN '06-Haziran' 
WHEN 7 THEN '07-Temmuz' WHEN 8 THEN '08-Ağustos' WHEN 9 THEN '09-Eylül' 
WHEN 10 THEN '10-Ekim' WHEN 11 THEN '11-Kasim' WHEN 12 THEN '12-Aralik' END 'Ay',
CONVERT(SMALLDATETIME,INV.DATE_,104)  'Tarih'

FROM 
LG_001_01_STLINE STL (NOLOCK) 
LEFT OUTER JOIN LG_001_ITEMS ITM (NOLOCK) ON ITM.LOGICALREF = STL.STOCKREF AND STL.LINETYPE=0 
LEFT OUTER JOIN LG_001_SRVCARD SRV (NOLOCK) ON SRV.LOGICALREF = STL.STOCKREF AND STL.LINETYPE=4
LEFT OUTER JOIN LG_001_ITEMS DEM (NOLOCK) ON DEM.LOGICALREF = STL.STOCKREF AND STL.LINETYPE=8
LEFT OUTER JOIN LG_001_CLCARD CL (NOLOCK) ON CL.LOGICALREF=STL.CLIENTREF
LEFT OUTER JOIN LG_001_UNITSETL  UNIT (NOLOCK) ON UNIT.LOGICALREF = STL.UOMREF
LEFT OUTER JOIN LG_001_01_INVOICE INV (NOLOCK) ON INV.LOGICALREF=STL.INVOICEREF
LEFT OUTER JOIN LG_001_EMUHACC ACC (NOLOCK) ON ACC.LOGICALREF=STL.VATACCREF
LEFT OUTER JOIN LG_001_EMUHACC ACC1 (NOLOCK) ON ACC1.LOGICALREF=STL.PRACCREF
WHERE  
INV.CANCELLED=0
AND STL.LINETYPE IN (0,4,8)
--AND STL.TRCODE IN (3,8,9)
AND STL.INVOICEREF > 0 --AND INV.FICHENO='GIB2021000000083'
AND INV.DATE_ BETWEEN @begdate AND @enddate
--AND INV.DATE_ BETWEEN '20210731' and '20210731'
and INV.TRCODE NOT IN (26)

UNION ALL

SELECT 
CLF.TRCODE 'Fatura Türü',
CLF.FICHENO 'Fatura Numarası',
CLF.DOCODE 'Fatura Belge Numarası',
CLF.DATE_ 'Fatura Tarihi',
CASE WHEN (CLF.ACCOUNTED=1 )  THEN ' Muhasebeleşmiş' else  'Muhasebeleşmemiş' END 'Durum',
'' AS 'Malzeme/Hizmet_Kodu',
--'' AS 'Döküman İzleme Numarası',
CL.LINEEXP 'Fatura Açıklaması',
CL.TRCODE,
'',
'',
'' AS 'Malzeme Açıklaması',
'' 'Müsteri Kodu',
'' 'Müsteri Ünvani',

''  'Hareket_Miktari ',
'' 'Birimi',
'' 'Birim Fiyat',
''   'Matrah ',
CL.VATRATE 'Kdv Oranı',
ROUND(CL.BRUTAMOUNTTR*CL.VATRATE/100,2)  'Kdv Tutarı', 

SUBSTRING(acc.CODE,1,4) 'KDV Kebir Hesabı',
ACC.CODE 'Kdv Hesap Kodu', 
ACC.DEFINITION_ 'Kdv Hesap Açıklaması',

SUBSTRING(ACC1.CODE,1,4) 'Tev.KDV Kebir Hesabı',
ACC1.CODE 'Tev.KDV Hesap Kodu', 
ACC1.DEFINITION_ ' Tev.KDV Hesap Açıklaması',

ISNULL(ROUND(CASE WHEN CL.VATDEDUCTACCREF>0 THEN (CL.BRUTAMOUNTTR*CL.VATRATE/100) * CL.DEDUCTIONPART1/(NULLIF(CL.DEDUCTIONPART2,0)) ELSE 0 END ,2),0) 'Tev.Kdv Tutarı', 
ROUND(CL.BRUTAMOUNTTR*CL.VATRATE/100,2) 'TOPLAM KDV TUTARI',


YEAR( CLF.DATE_) 'Yil' , 
CASE MONTH(CLF.DATE_)WHEN 1 THEN '01-Ocak' WHEN 2 THEN '02-subat' WHEN 3 THEN '03-Mart' 
WHEN 4 THEN '04-Nisan' WHEN 5 THEN '05-Mayis' WHEN 6 THEN '06-Haziran' 
WHEN 7 THEN '07-Temmuz' WHEN 8 THEN '08-Ağustos' WHEN 9 THEN '09-Eylül' 
WHEN 10 THEN '10-Ekim' WHEN 11 THEN '11-Kasim' WHEN 12 THEN '12-Aralik' END 'Ay',
CONVERT(SMALLDATETIME,CLF.DATE_,104)  'Tarih'

FROM 
LG_001_01_CLFLINE CL (NOLOCK) 
LEFT OUTER JOIN LG_001_01_CLFICHE CLF ON CLF.LOGICALREF=CL.SOURCEFREF
LEFT OUTER JOIN LG_001_EMUHACC ACC (NOLOCK) ON ACC.LOGICALREF=CL.VATRACCREF
LEFT OUTER JOIN LG_001_EMUHACC ACC1 (NOLOCK) ON ACC1.LOGICALREF=CL.VATDEDUCTACCREF
WHERE CL.CANCELLED=0   AND ACC.CODE IS NOT NULL 
AND CLF.DATE_ BETWEEN @begdate AND @enddate


